# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "2626d222-75b1-440c-911c-3be7afc8db8f"
published = 2013-07-05 22:34:28-04:00
title = "Franconia Notch State Park"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-franconia-notch-state-park/P1070307-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-franconia-notch-state-park/P1070349-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-franconia-notch-state-park/P1070359-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-franconia-notch-state-park/P1070360-raw-P1070375-raw-saturation.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-franconia-notch-state-park/P1070378-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-franconia-notch-state-park/P1070386-raw.jpg"
gallery = "main"
alt = ""
