# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

uuid = "775147ea-8b84-43a2-a5c5-827839af264a"
published = 2025-03-01 00:00:00-04:00
title = "Placeholder"
tags = ["dance", "music", "technology", "videos"]
