# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "582ed3fa-c69d-401a-917a-8b2b6bed3b33"
published = 2013-11-20 21:01:56-05:00
title = "Cows in a Field"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-11-21-cows-in-a-field/P1080825-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-11-21-cows-in-a-field/P1080847-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-11-21-cows-in-a-field/P1080862-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-11-21-cows-in-a-field/P1080877-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-11-21-cows-in-a-field/P1080908-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-11-21-cows-in-a-field/P1080933-raw.jpg"
gallery = "main"
alt = ""
