# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "b3fc46c1-d879-4d1e-8e17-d3c733bde63c"
published = 2013-02-20 20:14:33-05:00
title = "The Flurry"
tags = ["dance", "photos", "videos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030388-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030395-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030419-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030421-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030429-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030434-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030465-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030466-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030473-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030484-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030499-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030513-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030556-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030574-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030581-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030656-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030676-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030687-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030696-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030709-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030742-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030748-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030800-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-21-the-flurry/P1030841.JPG"
gallery = "main"
alt = ""
