# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

uuid = "554544c2-9951-417a-8dc1-b8d38f54539f"
published = 2025-05-01 00:00:00-04:00
title = "Placeholder"
tags = ["dance"]
