#!/bin/bash

# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

set -euxo pipefail

reuse lint

black --check --diff .
isort --check --diff .
mypy
pytest -m 'not output and not slow'

ninja
ninja -t cleandead
# TODO: https://github.com/ninja-build/ninja/issues/2617 - Delete this.
find output work -depth -type d -empty -print -delete

# TODO: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849473 - Validate
# html.
# TODO: https://github.com/gjtorikian/html-proofer/pull/717 - Remove
# --empty-alt-ignore
htmlproofer \
  --check-favicon \
  --check-opengraph \
  --disable-external \
  --empty-alt-ignore \
  --url-swap '/feed/\Z:/feed/index.xml,\Ahttps\://david\.mandelberg\.org(/|\Z):/' \
  output
pytest -m 'output and not slow' --no-cov
