#!/bin/bash

# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

set -euxo pipefail

reuse lint

black --check --diff .
isort --check --diff .
mypy
pytest

ninja
ninja -t cleandead
# TODO: https://github.com/ninja-build/ninja/issues/2617 - Delete this.
find output work -depth -type d -empty -print -delete

htmlproofer \
  --check-favicon \
  --url-swap '/feed/\Z:/feed/index.xml' \
  output
