# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

source_paths = [
  "../private/media",
  "../private/posts",
  "../private/third_party",
  "compress.ninja.jinja",
  "css",
  "errors",
  "htaccess.jinja",
  "include",
  "media",
  "posts",
  "src",
  "standalone",
]
build_paths = [
  "output",
  "work",
]
python_paths = [
  "src",
]
ninja_templates = [
  "compress.ninja.jinja",
  "css/build.ninja.jinja",
  "media/build.ninja.jinja",
]
templates = [
  "css/common.less.jinja",
  "errors/403/index.html.jinja",
  "errors/404/index.html.jinja",
  "htaccess.jinja",
  "posts/2009-06-16-hello-world/index.html.jinja",
  "posts/2009-09-16-student-union-elections-server-side/index.html.jinja",
  "posts/2009-09-24-polyball-bounce-0-1-0-released/index.html.jinja",
  "posts/2009-09-30-polyball-bounce-0-2-0-released/index.html.jinja",
  "posts/2009-10-04-polyball-bounce-0-2-1-released-goals-for-future-release/index.html.jinja",
  "posts/2010-10-09-department-of-survival/index.html.jinja",
  "posts/2013-02-12-snow-photos/index.html.jinja",
  "posts/2013-02-21-the-flurry/index.html.jinja",
  "posts/2013-02-21-saratoga-spa/index.html.jinja",
  "posts/2013-03-24-running-fox-farm/index.html.jinja",
  "posts/2013-04-06-montpelier-vt/index.html.jinja",
  "posts/2013-04-14-automatic-list-filtering-with-procmail/index.html.jinja",
  "posts/2013-05-05-neffa/index.html.jinja",
  "posts/2013-05-11-breton-meadow-farm-day-1/index.html.jinja",
  "posts/2013-05-19-lexington-muster/index.html.jinja",
  "posts/2013-05-19-breton-meadow-farm-day-2/index.html.jinja",
  "posts/2013-05-19-cobb-hill/index.html.jinja",
  "posts/2013-05-25-nature-in-the-rain/index.html.jinja",
  "posts/2013-06-02-shelburne-falls/index.html.jinja",
  "posts/2013-06-02-breton-meadow-farm/index.html.jinja",
  "posts/2013-06-09-bare-hill-wildlife-sanctuary/index.html.jinja",
  "posts/2013-06-18-backyard-flora-and-fauna/index.html.jinja",
  "posts/2013-06-22-mt-hope-cemetery-acton-ma/index.html.jinja",
  "posts/2013-07-06-franconia-notch-state-park/index.html.jinja",
  "posts/2013-07-06-nordic-fiddles-and-feet/index.html.jinja",
  "posts/2013-08-17-europe-trip/index.html.jinja",
  "posts/2013-09-15-great-brook-farm-state-park/index.html.jinja",
  "posts/2013-09-29-french-king-bridge/index.html.jinja",
  "posts/2013-10-26-bigelow-hollow-state-park/index.html.jinja",
  "posts/2013-11-21-cows-in-a-field/index.html.jinja",
  "posts/2013-12-15-vancouver-and-canadian-rockies/index.html.jinja",
  "posts/2013-12-22-exploring/index.html.jinja",
  "posts/2014-02-01-ski-dance/index.html.jinja",
  "posts/2014-02-17-horses-and-snow/index.html.jinja",
  "posts/2014-02-17-adventure-for-tufa/index.html.jinja",
  "posts/2014-04-19-edinburgh-and-london/index.html.jinja",
  "posts/2014-04-19-family-trips/index.html.jinja",
  "posts/2014-04-21-salisbury-beach-state-reservation/index.html.jinja",
  "posts/2014-05-04-museum-of-science-and-chinatown/index.html.jinja",
  "posts/2014-05-30-longwood-gardens/index.html.jinja",
  "posts/2014-06-01-great-meadows-national-wildlife-refuge/index.html.jinja",
  "posts/2014-06-22-minute-man-air-field/index.html.jinja",
  "posts/2022-01-01-placeholder/index.html.jinja",
  "posts/2024-06-01-placeholder/index.html.jinja",
  "posts/2024-07-01-placeholder/index.html.jinja",
  "posts/2024-08-01-placeholder/index.html.jinja",
  "posts/2024-09-01-placeholder/index.html.jinja",
  "posts/2024-10-01-placeholder/index.html.jinja",
  "posts/2024-11-01-placeholder/index.html.jinja",
  "posts/2024-12-01-placeholder/index.html.jinja",
  "posts/2025-01-01-placeholder/index.html.jinja",
  "posts/2025-02-01-placeholder/index.html.jinja",
  "posts/2025-03-01-placeholder/index.html.jinja",
  "posts/2025-04-02-placeholder/index.html.jinja",
  "posts/2025-05-01-placeholder/index.html.jinja",
  "posts/feeds.atom.jinja",
  "posts/lists.html.jinja",
  "standalone/about/index.html.jinja",
  "standalone/licenses/index.html.jinja",
]
