# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

source_paths = [
  "../private/media",
  "css",
  "errors",
  "htaccess.jinja",
  "include",
  "media",
  "posts",
  "src",
  "standalone",
]
build_paths = [
  "output",
  "work",
]
python_paths = [
  "src",
]
ninja_templates = [
  "css/build.ninja.jinja",
  "media/build.ninja.jinja",
]
templates = [
  "errors/403/index.html.jinja",
  "errors/404/index.html.jinja",
  "htaccess.jinja",
  "posts/2009-06-16-hello-world/index.html.jinja",
  "posts/2022-01-01-placeholder/index.html.jinja",
  "posts/2024-06-01-placeholder/index.html.jinja",
  "posts/2024-07-01-placeholder/index.html.jinja",
  "posts/2024-08-01-placeholder/index.html.jinja",
  "posts/2024-09-01-placeholder/index.html.jinja",
  "posts/2024-10-01-placeholder/index.html.jinja",
  "posts/2024-11-01-placeholder/index.html.jinja",
  "posts/2024-12-01-placeholder/index.html.jinja",
  "posts/2025-01-01-placeholder/index.html.jinja",
  "posts/2025-02-01-placeholder/index.html.jinja",
  "posts/2025-03-01-placeholder/index.html.jinja",
  "posts/2025-04-02-placeholder/index.html.jinja",
  "posts/2025-05-01-placeholder/index.html.jinja",
  "posts/feeds.xml.jinja",
  "posts/lists.html.jinja",
  "standalone/about/index.html.jinja",
]
