# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

source_paths = [
  "../private/media",
  "css",
  "include",
  "media",
  "posts",
  "src",
  "standalone",
]
build_paths = [
  "output",
  "work",
]
python_paths = [
  "src",
]
ninja_templates = [
  "css/build.ninja.jinja",
  "media/build.ninja.jinja",
]
templates = [
  "posts/2024-06-01-placeholder/index.html.jinja",
  "standalone/about/index.html.jinja",
]
