#!/bin/bash

# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

set -euxo pipefail

/usr/sbin/apache2 -D FOREGROUND -f "$PWD/apache2.conf"
