#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

# See
# https://web.archive.org/web/20231208050359/https://bz.apache.org/bugzilla/show_bug.cgi?id=50669
# for why this is so complicated. process_group=0 seems to prevent SIGWINCH.

import pathlib
import subprocess
import sys

if __name__ == "__main__":
    process = subprocess.Popen(
        (
            "/usr/sbin/apache2",
            "-D",
            "FOREGROUND",
            "-f",
            f"{pathlib.Path.cwd()}/apache2.conf",
        ),
        process_group=0,
    )
    try:
        process.wait()
    except KeyboardInterrupt:
        process.terminate()
        process.wait()
    sys.exit(process.returncode)
