#!/bin/bash

# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

pytest -m slow --no-cov
htmlproofer \
  --check-external-hash \
  --empty-alt-ignore \
  --url-swap '/feed/\Z:/feed/index.atom,\Ahttps\://david\.mandelberg\.org(/|\Z):/' \
  output
