#!/bin/bash

# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

set -euxo pipefail

pytest -m slow --no-cov --numprocesses=auto --dist=worksteal src
htmlproofer \
  --check-external-hash \
  --external_only \
  output
