#!/bin/bash

# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

set -euxo pipefail

pytest -m slow --no-cov --numprocesses=auto --dist=worksteal src

# TODO: https://github.com/gjtorikian/html-proofer/pull/717 - Remove
# --empty-alt-ignore
htmlproofer \
  --check-favicon \
  --check-opengraph \
  --disable-external \
  --empty-alt-ignore \
  --url-swap '/feed/\Z:/feed/index.atom,\Ahttps\://david\.mandelberg\.org(/|\Z):/' \
  output
htmlproofer \
  --check-external-hash \
  --external_only \
  --file-ignore '/^output/([0-9]{4}|page|tag)/.*/,output/index.html' \
  output
