# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "7dcf05fa-967a-4ebc-a9db-e9ac9d6fb1ef"
published = 2013-08-17 15:26:28-04:00
title = "Europe Trip"
tags = ["photos", "technology"]
comments = [
  "5815d35e-ff34-4017-8782-5a2024711df7",
  "52783a5c-73d5-4bda-92db-0929383b8c6e",
  "7afb1b25-2e04-4209-9d4c-51de406cdbff",
]

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070634-raw.jpg"
gallery = "2013-07-27"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070635-raw.jpg"
gallery = "2013-07-27"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070636-raw.jpg"
gallery = "2013-07-27"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070637-raw.jpg"
gallery = "2013-07-27"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070638-raw.jpg"
gallery = "2013-07-27"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070642-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070653-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070655-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070656-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070657-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070661-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070672-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070674-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070675-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070676-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070678-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070679-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070681-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070682-raw.jpg"
gallery = "2013-08-02"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070689-raw.jpg"
gallery = "2013-08-03"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070695-raw.jpg"
gallery = "2013-08-03"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070699-raw.jpg"
gallery = "2013-08-03"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070703-raw.jpg"
gallery = "2013-08-03"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070712-raw.jpg"
gallery = "2013-08-03"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070732-raw.jpg"
gallery = "2013-08-04"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070734-raw-P1070749-raw-brightness-saturation-crop.jpg"
gallery = "2013-08-05"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070798-raw.jpg"
gallery = "2013-08-05"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070827-raw.jpg"
gallery = "2013-08-05"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070835-raw.jpg"
gallery = "2013-08-05"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070837-raw-P1070857-raw-contrast-saturation.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070896-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070912-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070917-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070919-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070923-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070932-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070939-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070943-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070979-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070983-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070984-raw-P1070990-raw-brightness-saturation-contrast-crop.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1070993-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080013-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080016-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080021-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080033-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080035-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080036-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080037-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080039-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080043-raw-P1080059-raw-brightness-saturation.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080065-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080082-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080083-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080093-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080094-raw-P1080121-raw-brightness-saturation.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080122-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080126-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080131-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080133-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080135-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080151-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080153-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080155-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080162-raw-P1080175-raw-brightness-saturation.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080179-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080185-raw.jpg"
gallery = "2013-08-07"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080191-raw.jpg"
gallery = "2013-08-08-finse"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080208-raw.jpg"
gallery = "2013-08-08-finse"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080213-raw.jpg"
gallery = "2013-08-08-finse"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080215-raw.jpg"
gallery = "2013-08-08-finse"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080217-raw.jpg"
gallery = "2013-08-08-finse"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080221-raw.jpg"
gallery = "2013-08-08-finse"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080222-raw.jpg"
gallery = "2013-08-08-finse"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080223-raw.jpg"
gallery = "2013-08-08-flam-railway"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080224-raw.jpg"
gallery = "2013-08-08-flam-railway"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080252-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080254-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080261-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080264-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080265-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080266-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080269-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080277-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080283-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080293-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080296-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080300-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080316-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080328-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080333-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080336-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080345-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080347-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080355-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080360-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080364-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080366-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080372-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080392-raw-P1080403-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080404-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080407-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-08-17-europe-trip/P1080410-raw.jpg"
gallery = "2013-08-08-flam"
alt = ""
