# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "0781880d-27ad-48e7-ac87-9bb4be7d2fa7"
published = 2014-05-03 23:35:46-04:00
title = "Museum of Science and Chinatown"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1100994-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1100996-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1100998-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110001-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110008-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110013-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110032-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110043-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110057-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110058-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110065-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110069-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110070-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110074-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110075-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110076-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110080-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110087-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110090-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110096-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110097-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-05-04-museum-of-science-and-chinatown/P1110101-raw.jpg"
gallery = "main"
alt = ""
