# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "c6049cbc-5553-48aa-bb5e-8464e08f833c"
published = 2013-07-06 14:48:30-04:00
title = "Nordic Fiddles and Feet"
tags = ["dance", "photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070388-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070389-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070404-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070435-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070439-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070452-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070461-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070498-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070507-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070524-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070546-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070555-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070556-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070563-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070572-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070575-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-07-06-nordic-fiddles-and-feet/P1070605-raw.jpg"
gallery = "main"
alt = ""
