# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

uuid = "77ac8b73-be27-4d16-9974-f055e3991946"
published = 2024-11-01 00:00:00-04:00
title = "Placeholder"
tags = ["dance"]
