# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

uuid = "a791c4a6-bd53-4b5f-844b-3119f659097d"
published = 2025-02-01 00:00:00-04:00
title = "Placeholder"
tags = ["dance"]
