# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "ec7593b2-18be-4002-ba07-1da56fc51a03"
published = 2014-06-21 21:12:35-04:00
title = "Minute Man Air Field"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110486-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110490-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110499-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110500-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110504-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110509-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110526-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110557-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110564-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110578-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110582-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110589-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-22-minute-man-air-field/P1110591-raw.jpg"
gallery = "main"
alt = ""
