# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "540fcf5a-4947-4c26-8d13-8712092d6722"
published = 2013-05-19 16:40:14-04:00
title = "Breton Meadow Farm, Day 2"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-breton-meadow-farm-day-2/P1050954-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-breton-meadow-farm-day-2/P1050980-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-breton-meadow-farm-day-2/P1050986-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-breton-meadow-farm-day-2/P1060020-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-breton-meadow-farm-day-2/P1060037-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-breton-meadow-farm-day-2/P1060060-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-breton-meadow-farm-day-2/P1060078-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-breton-meadow-farm-day-2/P1060109-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-breton-meadow-farm-day-2/P1060113-raw.jpg"
gallery = "main"
alt = ""
