# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "1a360c36-8226-4eed-81c3-aab09b1f43b1"
published = 2009-09-29 23:23:28-04:00
title = "Polyball Bounce 0.2.0 Released"
tags = ["technology"]

[[media.items]]
type = "image"
source = "../private/posts/2009-09-30-polyball-bounce-0-2-0-released/Screenshot-Polyball-Bounce-1.png"
alt = "Polyball Bounce 0.2.0"
main = true

[[media.items]]
type = "image"
source = "../private/posts/2009-09-30-polyball-bounce-0-2-0-released/Screenshot-Configure-Polyball-Bounce.png"
alt = "Polyball Bounce 0.2.0: Configure"
main = true
