# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "1c4b127e-cbdb-410d-bb28-44d40eae641d"
published = 2013-10-26 19:28:13-04:00
title = "Bigelow Hollow State Park"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080701-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080703-raw-unsharp.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080714-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080722-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080728-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080736-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080757-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080760-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080763-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080774-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080778-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080788-raw-unsharp.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080794-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080796-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080802-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-10-26-bigelow-hollow-state-park/P1080809-raw.jpg"
gallery = "main"
alt = ""
