# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "90df27b3-11f5-4cbf-a4e7-47cc2089f2da"
published = 2013-06-18 00:14:45-04:00
title = "Backyard Flora and Fauna"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-06-18-backyard-flora-and-fauna/P1070087-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-18-backyard-flora-and-fauna/P1070088-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-18-backyard-flora-and-fauna/P1070092-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-18-backyard-flora-and-fauna/P1070113-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-18-backyard-flora-and-fauna/P1070125-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-18-backyard-flora-and-fauna/P1070133-raw.jpg"
gallery = "main"
alt = ""
