# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "b2690a10-b6c5-41fe-b433-cb82f58cbd75"
published = 2013-06-08 20:50:34-04:00
title = "Bare Hill Wildlife Sanctuary"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1060985-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1060986-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1060993-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1060995-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1060998-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1070006-raw-P1070008-raw_hdr_pregamma_1_mantiuk06_contrast_mapping_0.8_saturation_factor_1.75_detail_factor_1-levels-crop.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1070015-raw-P1070044-raw-saturation-crop.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1070050-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1070057-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1070060-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1070064-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1070070-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-09-bare-hill-wildlife-sanctuary/P1070073-raw.jpg"
gallery = "main"
alt = ""
