# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "7d95d59b-d7e0-40f3-80aa-e86c3e0878b7"
published = 2009-06-16 20:38:10+00:00
title = "Hello World!"
