# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "4c179bcb-2685-4d5b-88ae-1c71c9c18d65"
published = 2013-05-19 16:40:13-04:00
title = "Lexington Muster"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050860-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050865-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050868-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050874-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050875-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050882-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050888-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050897-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050900-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050905-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050908-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050911-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050916-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-19-lexington-muster/P1050920-raw.jpg"
gallery = "main"
alt = ""
