# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "1eb24715-a942-4e3b-9683-c8d327622157"
published = 2013-09-15 19:15:07-04:00
title = "Great Brook Farm State Park"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080467-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080469-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080473-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080486-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080495-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080496-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080513-raw-unsharp.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080515-raw-unsharp.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080521-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080533-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080542-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080548-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080566-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080569-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080570-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-09-15-great-brook-farm-state-park/P1080572-raw.jpg"
gallery = "main"
alt = ""
