# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "fa6f02f7-a393-45e8-8625-6736b4946166"
published = 2014-06-29 19:51:56-04:00
title = "Boxborough and Stow"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110593-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110594-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110597-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110604-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110607-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110609-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110613-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110617-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110637-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110641-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110649-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110658-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110659-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110668-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110683-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110700-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-29-boxborough-and-stow/P1110706-raw.jpg"
gallery = "main"
alt = ""
