# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "e3d608b1-a980-461e-9719-4216789bdc1e"
published = 2014-02-17 11:53:00-05:00
title = "Horses and Snow"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100415-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100419-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100422-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100429-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100440-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100442-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100444-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100452-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100456-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100457-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100458-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100461-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100465-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100467-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100470-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100472-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-02-17-horses-and-snow/P1100481-raw.jpg"
gallery = "main"
alt = ""
