# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "187bc057-fbd1-4f51-9b81-14208a83253e"
published = 2013-05-24 21:58:16-04:00
title = "Nature in the Rain"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-05-25-nature-in-the-rain/P1060261-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-25-nature-in-the-rain/P1060267-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-25-nature-in-the-rain/P1060296-raw.jpg"
gallery = "main"
alt = ""
