# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

uuid = "ac05ec4b-c85c-43be-ae98-ae3c9896458f"
published = 2025-04-01 22:00:00-04:00
title = "Placeholder"
tags = ["dance"]
