# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "3d2ab80e-6fe9-4fdd-9a83-8e4b10e856b1"
published = 2013-02-11 22:18:47-05:00
title = "Snow Photos"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030242-raw.JPG"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030252-raw.JPG"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030256-raw.JPG"
gallery = "main"
alt = ""
description_template = "posts/2013-02-12-snow-photos/P1030256-raw.html.jinja"

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030266-raw.JPG"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030270-raw.JPG"
gallery = "main"
opengraph = true
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030285-raw.JPG"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030288-raw.JPG"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030308-raw.JPG"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030324-raw-P1030337-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030356-raw.JPG"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030360-raw.JPG"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030363-raw.JPG"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-02-12-snow-photos/P1030374-raw.JPG"
gallery = "main"
alt = ""
