# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "65a64c28-c844-4f46-91e5-a870487f43d8"
published = 2013-03-23 21:06:14-04:00
title = "Running Fox Farm"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-03-24-running-fox-farm/P1030942-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-03-24-running-fox-farm/P1030943-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-03-24-running-fox-farm/P1030945-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-03-24-running-fox-farm/P1030950-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-03-24-running-fox-farm/P1030953-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-03-24-running-fox-farm/P1030958-raw.jpg"
gallery = "main"
alt = ""
description_template = "posts/2013-03-24-running-fox-farm/P1030958-raw.html.jinja"

[[media.items]]
type = "image"
source = "../private/posts/2013-03-24-running-fox-farm/P1030972-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-03-24-running-fox-farm/P1030987-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-03-24-running-fox-farm/P1030992-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-03-24-running-fox-farm/P1030995-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-03-24-running-fox-farm/P1040007-raw-no-plates.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-03-24-running-fox-farm/P1040009-raw.jpg"
gallery = "main"
alt = ""
