# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "9202c498-a358-4de5-8c3e-f8eb55804477"
published = 2013-05-11 12:13:05-04:00
title = "Breton Meadow Farm, Day 1"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050269-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050340-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050344-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050375-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050395-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050403-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050413-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050415-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050418-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050421-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050423-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050427-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050444-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050462-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050510-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050531-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050534-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050543-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050555-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050583-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050611-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050616-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050654-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-05-11-breton-meadow-farm-day-1/P1050674-raw.jpg"
gallery = "main"
alt = ""
