# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "bf188fc6-81f7-4a28-a935-f12ae4a254fa"
published = 2014-06-01 19:19:35-04:00
title = "Great Meadows National Wildlife Refuge"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2014-06-01-great-meadows-national-wildlife-refuge/P1110381-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-01-great-meadows-national-wildlife-refuge/P1110386-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-01-great-meadows-national-wildlife-refuge/P1110398-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-01-great-meadows-national-wildlife-refuge/P1110417-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-01-great-meadows-national-wildlife-refuge/P1110435-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-01-great-meadows-national-wildlife-refuge/P1110442-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2014-06-01-great-meadows-national-wildlife-refuge/P1110447-raw.jpg"
gallery = "main"
alt = ""
