# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "36e6ef35-843b-4789-aa7d-df2b99cc709f"
published = 2013-06-02 15:15:06-04:00
title = "Breton Meadow Farm"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-breton-meadow-farm/P1060705-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-breton-meadow-farm/P1060790-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-breton-meadow-farm/P1060818-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-breton-meadow-farm/P1060835-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-breton-meadow-farm/P1060887-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-breton-meadow-farm/P1060891-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-breton-meadow-farm/P1060893-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-breton-meadow-farm/P1060952-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-breton-meadow-farm/P1060980-raw.jpg"
gallery = "main"
alt = ""
