# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "0c4d5b15-6d10-4585-a34c-061af6a40e35"
published = 2009-09-16 00:08:56-04:00
title = "Student Union Elections (Server Side)"
tags = ["technology"]
