# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

[[media.items]]
type = "image"
source = "../private/errors/404/P1250746-raw-unsharp.jpg"
alt = """\
  Vuvuzela held by a plastic truss, with a balloon over the mouthpiece. Coming \
  out of the other end of the balloon is a tube. The other end of that tube is \
  duct taped to a pink plastic box.\
"""
main = true
