# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

url = "https://david.mandelberg.org"
title = "David Mandelberg"
author = "David Mandelberg"
language = "en-US"
direction = "ltr"
