# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "d1c00b1e-4d4a-4297-ab1f-02d8e4f1c642"
published = 2009-09-23 23:49:55-04:00
title = "Polyball Bounce 0.1.0 Released"
tags = ["technology"]
