# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "036d043a-cdf6-4dc1-8bbc-349d4738bf69"
published = 2013-06-02 13:25:52-04:00
title = "Shelburne Falls"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060448-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060457-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060464-raw-perspective-crop.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060471-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060473-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060488-raw-P1060506-raw-crop-levels.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060510-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060513-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060524-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060552-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060577-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060587-raw_pregamma_1_mantiuk06_contrast_mapping_0.75_saturation_factor_1.5_detail_factor_1-levels.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060594-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060597-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060606-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060610-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060612-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060622-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060644-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-06-02-shelburne-falls/P1060652-raw.jpg"
gallery = "main"
alt = ""
