# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: CC-BY-4.0

uuid = "b263433b-0eb8-49c8-922e-4b31badf873a"
published = 2013-12-22 18:11:52-05:00
title = "Exploring"
tags = ["photos"]

[[media.items]]
type = "image"
source = "../private/posts/2013-12-22-exploring/P1100206-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-12-22-exploring/P1100212-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-12-22-exploring/P1100213-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-12-22-exploring/P1100216-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-12-22-exploring/P1100217-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-12-22-exploring/P1100224-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-12-22-exploring/P1100232-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-12-22-exploring/P1100234-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-12-22-exploring/P1100238-rawbw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-12-22-exploring/P1100252-raw.jpg"
gallery = "main"
alt = ""

[[media.items]]
type = "image"
source = "../private/posts/2013-12-22-exploring/P1100271-raw.jpg"
gallery = "main"
alt = ""
